version: "3.8"
services:
  app:
    build: .
    container_name: my_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: pvz_db
    environment:
      POSTGRES_USER: pvz_user
      POSTGRES_PASSWORD: riop123455
      POSTGRES_DB: pvz_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
